version: "3.2"

services:
  db:
    container_name: hacker_lynx_dev_db
    restart: always
    image: postgres
    volumes: ["hacker_lynx_dev_db:/var/lib/postgresql/data"]
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: lynx_list_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: hacker_lynx_dev_app
    restart: always
    build:
      context: ..
      dockerfile: dev/Dockerfile
    tty: true
    stdin_open: true
    depends_on: [db]
    volumes: ["../..:/app"]
    ports: ["8800:8800"]
    environment:
      PG_HOST: db

volumes:
  hacker_lynx_dev_db:
